import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-br">
      <head>
        <link rel="preconnect" href="https://challenges.cloudflare.com" />
      </head>

      <body className={`${poppins.variable} antialiased`}>
        {children}

        {/* Script recomendado pelo Cloudflare */}
        <Script
          src="https://challenges.cloudflare.com/turnstile/v0/api.js"
          strategy="beforeInteractive"
          async
          defer
        />

        {/* Script flowbit para o tooltip */}
        <Script
          src="https://cdn.jsdelivr.net/npm/flowbite/dist/flowbite.min.js" strategy="beforeInteractive" defer />
      </body>
    </html>
  );
}

